using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Assignment02
{
    class Hero
    {
        //Random Number
        Random rnd = new Random();


        //************** Private Properties *********************
        private int strength;
        private int speed;
        private int health;
        private int randomNumber;

        //*************** Public Properties *********************
        public string name;

        //*************** Constructor Method ********************
        public Hero(string name)
        {
            this.name = name;
            generateAbilities();
        }

        //**************** Private Methods **********************
        private void generateAbilities()
        {
            //Random abilities generated by user
            this.strength = rnd.Next(1, 100) + 1;
            this.speed = rnd.Next(1, 100) + 1;
            this.health = rnd.Next(1, 100) + 1;
        }

        private bool hitAttempt()
        {
            this.randomNumber = rnd.Next(1, 100) + 1;
            // Console.WriteLine("{0}", this.randomNumber); For testing Purpose...!!!!

            if (this.randomNumber <= 20)
            {
                Console.WriteLine("Yeah..!!! Hero hits");
                return true;
            }
            else
            {
                Console.WriteLine("Oops..!! Hero misses the hit");
                return false;
            }

        }

        private int hitDamage()
        {
            this.randomNumber = rnd.Next(1, 6) + 1;
            // Console.WriteLine("i am here, {0}",randomNumber);..... ////// For Testing Purpose
            int damage = this.strength * this.randomNumber;
            return damage;
        }

        //*************** Public Methods ***********************
        public void fight()
        {

            if (hitAttempt() == true)
            {
                int damage = hitDamage();
                Console.WriteLine("The damage caused is: {0}", damage);
            }
        }

        public void show()
        {
            Console.WriteLine(" ********************* ");
            Console.WriteLine(" Strength of Hero : {0}", this.strength);
            Console.WriteLine(" Speed of Hero    : {0}", this.speed);
            Console.WriteLine(" Health of Hero   : {0}", this.health);
            Console.WriteLine(" ********************* ");
        }
    }
}
